### ISSUE TITLE
The training dataset is only 50, resulting in very poor MAE!

### ISSUE THREAD

**Issue by YanChen32** [vertaix/LLM-Prop#1]
I am deeply grateful for your inspiring contributions, which have profoundly influenced my research. Upon replicating your work, I have discerned that the high mean absolute error (MAE) values (~1.0) are attributable to the limited scale of the available dataset. 

I eagerly anticipate the release of additional data, perhaps around 1000 samples, to facilitate thorough testing prior to publication.

**Comment by Andrews2017** [comment]
Hi Yan Chen,

Thank you for reaching out and for being interested in our work. 

We have just made TextEdge (the full dataset we collected to train LLM-Prop) publicly available in the [LLM-Prop GitHub repository](https://github.com/vertaix/LLM-Prop/tree/main?tab=readme-ov-file#Data%20availability) (Data Availability section). Alternatively, you may also download it directly from [here](https://drive.usercontent.google.com/download?id=13lKJKWopYUAvydqOYJ3-OCJXWMa6kO7J&export=download&authuser=0).

Please, let me know if you have any other questions.

**Comment by YanChen32** [comment]
Thank you very much! I'm thrilled to have essentially replicated the MAE results using the complete TextEdge dataset. It's truly remarkable what LLM can accomplish! Regarding the significance of text description, semantic coherence, contextual relevance, and domain-specific terminology have a significant impact on results. Thus, which information in the text description is more pivotal for the final outcome?

**Comment by Andrews2017** [comment]
Thanks for the feedback Yan Chen! I am glad to hear that you could reproduce the results.

Regarding the information in the text description that influences the predictions more, we did not do a systematic study on this but it could be a very interesting idea to try out. However, we did check how removing space group information affected the results and observed a performance drop on all three property predictions, with the volume prediction being affected the most.

**Comment by YanChen32** [comment]
Thank you for your response and answer! I'll conduct further analysis on the importance of the information in the text description and provide feedback soon!
